[tool.black]
skip-string-normalization = true

[tool.pytest.ini_options]
testpaths = [
    "mpl_annotation_set/tests"
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
